<div class="img"><img src="images/badge-19.jpg" /></div>
<div class="img"><img src="images/badge-21.jpg" /></div>
<div class="img"><img src="images/badge-22.jpg" /></div>
<div class="img"><img src="images/badge-5.jpg" /></div>
<div class="img"><img src="images/badge-9.jpg" /></div>
<div class="img"><img src="images/badge-14.jpg" /></div>
<div class="img"><img src="images/badge-12.jpg" /></div>
<div class="img"><img src="images/badge-10.jpg" /></div>
<div class="img"><img src="images/badge-13.jpg" /></div>
<div class="img"><img src="images/badge-25.jpg" /></div>
<div class="img"><img src="images/badge-26.jpg" /></div>
<div class="img"><img src="images/badge-27.jpg" /></div>
<div class="img"><img src="images/badge-28.jpg" /></div>
<div class="img"><img src="images/badge-29.jpg" /></div>
<div class="img"><img src="images/badge-30.jpg" /></div>
<div class="img"><img src="images/badge-31.jpg" /></div>
<div class="img"><img src="images/badge-33.jpg" /></div>
<div class="img"><img src="images/badge-34.jpg" /></div>
<div class="img"><img src="images/badge-35.jpg" /></div>
<div class="img"><img src="images/badge-36.jpg" /></div>
<div class="img"><img src="images/badge-peace.png" /></div>
