<div class="img"><img src="images/badge-19.jpg" /></div>
<div class="img"><img src="images/badge-21.jpg" /></div>
<div class="img"><img src="images/badge-22.jpg" /></div>
<div class="img"><img src="images/badge-5.jpg" /></div>
<div class="img"><img src="images/badge-9.jpg" /></div>
<div class="img"><img src="images/badge-14.jpg" /></div>
<div class="img"><img src="images/badge-12.jpg" /></div>
<div class="img"><img src="images/badge-10.jpg" /></div>
<div class="img"><img src="images/badge-13.jpg" /></div>
<div class="img"><img src="images/badge-25.jpg" /></div>
<div class="img"><img src="images/badge-26.jpg" /></div>
<div class="img"><img src="images/badge-27.jpg" /></div>
<div class="img"><img src="images/badge-peace.png" /></div>
